services:
  # 1. Twoja aplikacja Next.js
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      # ... twoje stare zmienne ...
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - AUTH_URL=${AUTH_URL}
      # Konfiguracja S3 (MinIO)
      - S3_ENDPOINT=http://minio:9000
      - S3_REGION=eu-central-1
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      # Publiczny URL do wyświetlania zdjęć w przeglądarce
      - NEXT_PUBLIC_S3_HOSTNAME=localhost
      - NEXT_PUBLIC_S3_PORT=9000
      - AUTH_TRUST_HOST=true
    depends_on:
      - db
      - minio # Czekaj na start MinIO
    restart: always

  # 2. Baza Danych
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # 3. MinIO (Twój lokalny S3)
  minio:
    image: minio/minio
    ports:
      - "9000:9000" # API
    environment:
      MINIO_ROOT_USER: ${S3_USER}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

  # 4. Automat konfiguracyjny (Wersja kuloodporna)
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    environment:
      # Przekazujemy admina (musi pasować do sekcji minio!)
      S3_USER: ${S3_USER}
      S3_PASSWORD: ${S3_PASSWORD}
      # Przekazujemy dane nowego usera, które ma utworzyć
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    volumes:
      - ./create-buckets.sh:/create-buckets.sh
    entrypoint:
      - /bin/sh
      - /create-buckets.sh

volumes:
  postgres_data:
  minio_data: # Tutaj fizycznie będą leżeć zdjęcia